// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_wvdZjHxZHDqBqe4NQ1nngJxvhUf1Fn0',
    appId: '1:817710784140:web:768408497da2400d5ea5a9',
    messagingSenderId: '817710784140',
    projectId: 'garagem60storage',
    authDomain: 'garagem60storage.firebaseapp.com',
    storageBucket: 'garagem60storage.firebasestorage.app',
    measurementId: 'G-LQXCYY3KTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw3cnt-1QLmKYKLBCk0_zOVWC0bE6ilqI',
    appId: '1:817710784140:android:6d9b063b37f39e295ea5a9',
    messagingSenderId: '817710784140',
    projectId: 'garagem60storage',
    storageBucket: 'garagem60storage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVk1_IOVxW6zFM67YS1_m1ndsg5Fr9DUs',
    appId: '1:817710784140:ios:585d699c9331b8d85ea5a9',
    messagingSenderId: '817710784140',
    projectId: 'garagem60storage',
    storageBucket: 'garagem60storage.firebasestorage.app',
    iosBundleId: 'com.example.garagem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVk1_IOVxW6zFM67YS1_m1ndsg5Fr9DUs',
    appId: '1:817710784140:ios:585d699c9331b8d85ea5a9',
    messagingSenderId: '817710784140',
    projectId: 'garagem60storage',
    storageBucket: 'garagem60storage.firebasestorage.app',
    iosBundleId: 'com.example.garagem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_wvdZjHxZHDqBqe4NQ1nngJxvhUf1Fn0',
    appId: '1:817710784140:web:da632adb51fa220d5ea5a9',
    messagingSenderId: '817710784140',
    projectId: 'garagem60storage',
    authDomain: 'garagem60storage.firebaseapp.com',
    storageBucket: 'garagem60storage.firebasestorage.app',
    measurementId: 'G-QV854P25KS',
  );
}
