name: garagem
description: Aplicativo para gerenciar veículos e suas manutenções

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  http: ^0.13.5  # ou a versão mais recente
  shared_preferences: ^2.2.13  # ou a versão mais recente
  intl: ^0.17.0
  mask_text_input_formatter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
 
  uses-material-design: true

 