name: garagem
description: Aplicativo para gerenciar veículos e suas manutenções

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  http: ^1.3.0  # ou a versão mais recente
  shared_preferences: ^2.2.13  # ou a versão mais recente
  intl: ^0.20.2
  mask_text_input_formatter: ^2.3.0
  image_picker: ^1.0.7 # Add image_picker
  firebase_core: ^3.13.0 # Add firebase_core
  firebase_storage: ^12.4.5 # Add firebase_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Atualizado para a versão mais recente


flutter:
 
  uses-material-design: true

